const swaggerAutogen = require('swagger-autogen')();

const doc = {
  info: {
    version: '1.0.0',
    title: 'My API',
    description:
      'Documentation automatically generated by the <b>swagger-autogen</b> module.',
  },
  host: 'localhost:3000',
  basePath: '/',
  schemes: ['http', 'https'],
  consumes: ['application/json'],
  produces: ['application/json'],
  tags: [],
  securityDefinitions: {
    Bearer: {
      type: 'apiKey',
      name: 'Authorization',
      in: 'header',
      description: 'send JWT',
    },
  },
  definitions: {
    User: {
      type: 'object',
      properties: {
        id: {
          type: 'Integer',
        },
        userId: {
          type: 'String',
        },
        password: {
          type: 'String',
        },
        nickname: {
          type: 'String',
        },
        date: {
          type: 'String',
        },
      },
    },
    Todo: {
      type: 'object',
      properties: {
        user: {
          type: 'String',
        },
        perfection: {
          type: 'Number',
        },
        creativity: {
          type: 'Number',
        },
        difficulty: {
          type: 'Number',
        },
        concentration: {
          type: 'Number',
        },
        satisfaction: {
          type: 'Number',
        },
        date: {
          type: 'String',
        },
      },
    },
    Percent: {
      type: 'object',
      properties: {
        user: {
          type: 'String',
        },
        totalPercent: {
          type: 'Number',
        },
      },
    },
  },
};

const outputFile = './swagger_output.json';
const endpointsFiles = ['./app.js'];

swaggerAutogen(outputFile, endpointsFiles, doc);
